### ISSUE TITLE
"Create JavaDocs on all Elements" on Project level caused Plugin issue

### ISSUE THREAD

**Issue by Eric-Wiegman** [setial/intellij-javadocs#39]
<i>Observed on Windows 8.1, with IntelliJ IDEA Community Edition 14.1.1</i>

<b>Synopsis</b>
In Project window, I right-clicked the (Maven, using git plugin) Project root and selected the JavaDocs>Create JavaDocs on all Elements. This produced the error.

<b>IDE Fatal Error Message:</b>
Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document.

<b>Stack Trace</b>
<code>
Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document.
java.lang.RuntimeException: Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document.
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.beforeDocumentChanged(PostprocessReformattingAspect.java:284)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.beforeDocumentChangeOnUnlockedDocument(PsiDocumentManagerImpl.java:124)
	at com.intellij.psi.impl.PsiDocumentManagerBase.beforeDocumentChange(PsiDocumentManagerBase.java:636)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy20.beforeDocumentChange(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.doBeforeChangedUpdate(DocumentImpl.java:760)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:722)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:607)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:560)
	at com.intellij.psi.formatter.DocumentBasedFormattingModel.replaceWhiteSpace(DocumentBasedFormattingModel.java:134)
	at com.intellij.formatting.FormatProcessor.replaceWhiteSpace(FormatProcessor.java:411)
	at com.intellij.formatting.FormatProcessor.access$2400(FormatProcessor.java:40)
	at com.intellij.formatting.FormatProcessor$ApplyChangesState.doIteration(FormatProcessor.java:1442)
	at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1268)
	at com.intellij.formatting.FormatProcessor.doIterationsSynchronously(FormatProcessor.java:327)
	at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:314)
	at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:303)
	at com.intellij.formatting.FormatterImpl.adjustLineIndentsForRange(FormatterImpl.java:382)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$6.doPerform(CodeStyleManagerImpl.java:383)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:106)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:380)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatNewlyAddedElement(CodeStyleManagerImpl.java:314)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl$WriteJavaDocActionImpl.run(JavaDocWriterImpl.java:125)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.write(JavaDocWriterImpl.java:65)
	at com.github.setial.intellijjavadocs.action.JavaDocGenerateAction.processElement(JavaDocGenerateAction.java:99)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFile(JavaDocsGenerateAction.java:79)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:59)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:56)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:56)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:56)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFiles(JavaDocsGenerateAction.java:56)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.actionPerformed(JavaDocsGenerateAction.java:46)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</code>

**Comment by TSergey** [comment]
This should be fixed in https://github.com/setial/intellij-javadocs/releases/tag/intellij-javadocs-2.0.1
