### ISSUE TITLE
Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document.

### ISSUE THREAD

**Issue by YoReay** [setial/intellij-javadocs#41]
Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document.
java.lang.RuntimeException: Document is locked by write PSI operations. Use PsiDocumentManager.doPostponedOperationsAndUnblockDocument() to commit PSI changes to the document.
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.beforeDocumentChanged(PostprocessReformattingAspect.java:284)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.beforeDocumentChangeOnUnlockedDocument(PsiDocumentManagerImpl.java:124)
	at com.intellij.psi.impl.PsiDocumentManagerBase.beforeDocumentChange(PsiDocumentManagerBase.java:636)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy21.beforeDocumentChange(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:760)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:722)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:607)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:560)
	at com.intellij.psi.formatter.DocumentBasedFormattingModel.replaceWhiteSpace(DocumentBasedFormattingModel.java:134)
	at com.intellij.formatting.FormatProcessor.a(FormatProcessor.java:414)
	at com.intellij.formatting.FormatProcessor.access$2700(FormatProcessor.java:42)
	at com.intellij.formatting.FormatProcessor$ApplyChangesState.doIteration(FormatProcessor.java:1445)
	at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1271)
	at com.intellij.formatting.FormatProcessor.a(FormatProcessor.java:329)
	at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:316)
	at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:305)
	at com.intellij.formatting.FormatterImpl.adjustLineIndentsForRange(FormatterImpl.java:382)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$6.doPerform(CodeStyleManagerImpl.java:383)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:106)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:380)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatNewlyAddedElement(CodeStyleManagerImpl.java:314)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl$RemoveJavaDocActionImpl.run(JavaDocWriterImpl.java:165)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.remove(JavaDocWriterImpl.java:80)
	at com.github.setial.intellijjavadocs.action.JavaDocsRemoveAction.processElement(JavaDocsRemoveAction.java:25)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFile(JavaDocsGenerateAction.java:79)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.actionPerformed(JavaDocsGenerateAction.java:44)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by TSergey** [comment]
This should be fixed in https://github.com/setial/intellij-javadocs/releases/tag/intellij-javadocs-2.0.1
