### ISSUE TITLE
Version 2.1 fails to load in Intellij 15

### ISSUE THREAD

**Issue by rtennantventuretech** [setial/intellij-javadocs#45]
```

java.lang.NoClassDefFoundError: freemarker/cache/TemplateLoader
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:412)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: freemarker.cache.TemplateLoader PluginClassLoader[com.github.setial, 2.1.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 23 more
```

**Comment by TSergey** [comment]
Could you please check for updates of plugins? On intellij idea 15 should run javadocs plugin 3.1.0 version.

**Comment by rtennantventuretech** [comment]
Got it. Works. Thanks!
