### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by anoopsivarajan** [setial/intellij-javadocs#78]
The latest version is throwing Illegal state exception when I try to generate java doc on a class with errors.

Please find the below exception.

`Attempt to modify PSI for non-committed Document!
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:348)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:143)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:155)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:613)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.addJavaDoc(JavaDocWriterImpl.java:180)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.access$100(JavaDocWriterImpl.java:31)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl$WriteJavaDocActionImpl.run(JavaDocWriterImpl.java:125)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:174)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:214)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:105)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:216)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:172)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:155)
	at com.github.setial.intellijjavadocs.operation.impl.JavaDocWriterImpl.write(JavaDocWriterImpl.java:66)
	at com.github.setial.intellijjavadocs.action.JavaDocGenerateAction.processElement(JavaDocGenerateAction.java:119)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.processFile(JavaDocsGenerateAction.java:102)
	at com.github.setial.intellijjavadocs.action.JavaDocsGenerateAction.actionPerformed(JavaDocsGenerateAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:235)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:578)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:627)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:626)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by TSergey** [comment]
Try in 4.0.1 version
